service: amos-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  region: eu-west-1
  environment:
    PGHOST: ${.env:PGHOST}
    PGDATABASE: ${.env:PGDATABASE}
    PGUSER: ${.env:PGUSER}
    PGPASSWORD: ${.env:PGPASSWORD}
    PGPORT: ${.env:PGPORT}

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-python-requirements
